bump rel, remove all workarounds to build
we need to stick with -lm in make_build to fix build becuse from 4.16.0 it start screaming about:
error: undefined symbol: ceil